/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Service health and loaded model */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dataset counts and headline model performance */
        get: operations["stats_api_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** NASA sources behind the data */
        get: operations["sources_api_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/domain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tested input ranges per fuel (for UI controls) */
        get: operations["domain_api_domain_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/model": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Model card: metrics, calibration, bands, limits */
        get: operations["model_api_model_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experiments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Observed FLEX tests with filters */
        get: operations["list_experiments_api_experiments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experiments/{test_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One FLEX test with source and notes */
        get: operations["get_experiment_api_experiments__test_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/predict": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Fire Risk with evidence and explanation */
        post: operations["predict_api_predict_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/what-if": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compare two hypothetical scenarios */
        post: operations["what_if_api_what_if_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ranking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rank FLEX tests by predicted risk or burn time */
        get: operations["ranking_api_ranking_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ranking/conditions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rank tested atmospheres by observed sustained-combustion rate */
        get: operations["condition_ranking_api_ranking_conditions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/suppressants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Suppressant comparison from observed tests (no ML model) */
        get: operations["suppressants_api_suppressants_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/similar-experiments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Nearest tested FLEX conditions */
        post: operations["similar_api_similar_experiments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BandEvidence */
        BandEvidence: {
            /** @default evaluation */
            provenance: components["schemas"]["Provenance"];
            level: components["schemas"]["RiskLevel"];
            /** Tests */
            tests: number;
            /** Observed Sustained Rate */
            observed_sustained_rate: number;
            /** Ci Low */
            ci_low: number;
            /** Ci High */
            ci_high: number;
        };
        /** BandRow */
        BandRow: {
            level: components["schemas"]["RiskLevel"];
            /** Score From */
            score_from: number;
            /** Score To */
            score_to: number;
            /** Tests */
            tests: number;
            /** Sustained */
            sustained: number;
            /** Observed Sustained Rate */
            observed_sustained_rate: number;
            /** Ci Low */
            ci_low: number;
            /** Ci High */
            ci_high: number;
        };
        /** CalibrationBin */
        CalibrationBin: {
            /** Mean Predicted */
            mean_predicted: number;
            /** Observed Rate */
            observed_rate: number;
            /** Ci Low */
            ci_low: number;
            /** Ci High */
            ci_high: number;
            /** Tests */
            tests: number;
        };
        /** ConditionRank */
        ConditionRank: {
            /** Rank */
            rank: number;
            fuel: components["schemas"]["Fuel"];
            /** Pressure Level */
            pressure_level: string;
            /** Suppressant */
            suppressant: string;
            /** Oxygen Percent */
            oxygen_percent: number;
            /** Co2 Percent */
            co2_percent: number;
            /** He Percent */
            he_percent: number;
            /** Tests */
            tests: number;
            /** Sustained */
            sustained: number;
            /** Observed Rate */
            observed_rate: number;
            /** Ci Low */
            ci_low: number;
            /** Ci High */
            ci_high: number;
            /** Test Ids */
            test_ids: number[];
        };
        /** ConditionRankingResponse */
        ConditionRankingResponse: {
            /** @default observed */
            provenance: components["schemas"]["Provenance"];
            /** Method */
            method: string;
            /** Items */
            items: components["schemas"]["ConditionRank"][];
        };
        /**
         * Conditions
         * @description Conditions a user can set. These are exactly the final model's inputs; pressure, temperature
         *     and airflow are not inputs (FLEX: quiescent, ambient temperature; pressure dropped, decision D-001).
         * @example {
         *       "droplet_diameter_mm": 3,
         *       "fuel": "Methanol",
         *       "oxygen_percent": 21,
         *       "suppressant": "CO2",
         *       "suppressant_percent": 10
         *     }
         */
        Conditions: {
            fuel: components["schemas"]["Fuel"];
            /**
             * Oxygen Percent
             * @description O2 mole fraction in percent (air = 21).
             */
            oxygen_percent: number;
            /**
             * @description Added diluent gas; 'none' = O2/N2 only.
             * @default none
             */
            suppressant: components["schemas"]["Suppressant"];
            /**
             * Suppressant Percent
             * @description Suppressant mole fraction in percent.
             * @default 0
             */
            suppressant_percent: number;
            /**
             * Droplet Diameter Mm
             * @description Initial droplet diameter in mm.
             */
            droplet_diameter_mm: number;
        };
        /** Contribution */
        Contribution: {
            /**
             * Key
             * @enum {string}
             */
            key: "fuel" | "atmosphere" | "droplet_size";
            /** Label */
            label: string;
            /**
             * Impact
             * @description Fire Risk points relative to the average FLEX test
             */
            impact: number;
            /**
             * Direction
             * @enum {string}
             */
            direction: "raises" | "lowers" | "neutral";
        };
        /** DomainResponse */
        DomainResponse: {
            /** Fuels */
            fuels: {
                [key: string]: components["schemas"]["FuelDomain"];
            };
            /** Pressure Scope Atm */
            pressure_scope_atm: [
                number,
                number
            ];
            /** Notes */
            notes: string[];
        };
        /** Evidence */
        Evidence: {
            /** In Tested Range */
            in_tested_range: boolean;
            /**
             * Supported By Data
             * @description Close to a tested FLEX condition (not an extrapolation)
             */
            supported_by_data: boolean;
            /** Nearest Tested Distance */
            nearest_tested_distance: number;
            /** Support Radius */
            support_radius: number;
            /** Warnings */
            warnings: string[];
            band: components["schemas"]["BandEvidence"];
            /** Nearest Experiment Ids */
            nearest_experiment_ids: number[];
        };
        /** ExperimentCounts */
        ExperimentCounts: {
            /**
             * Total
             * @description All FLEX tests in NASA PSI-69
             */
            total: number;
            /**
             * In Model Scope
             * @description Tests used to train the model (0.7-1 atm, complete inputs)
             */
            in_model_scope: number;
            /** Extinction */
            extinction: number;
            /** Completion */
            completion: number;
            /** Disruption */
            disruption: number;
            /**
             * Sustained
             * @description Completion + disruption
             */
            sustained: number;
        };
        /** ExperimentDetail */
        ExperimentDetail: {
            /** @default observed */
            provenance: components["schemas"]["Provenance"];
            /** Test Id */
            test_id: number;
            /** Flex Identifier */
            flex_identifier: string;
            /** Datetime Gmt */
            datetime_gmt: string;
            fuel: components["schemas"]["Fuel"];
            /** Pressure Atm */
            pressure_atm: number | null;
            /** Pressure Level */
            pressure_level: string;
            /** Oxygen Percent */
            oxygen_percent: number;
            /** Nitrogen Percent */
            nitrogen_percent: number;
            /** Co2 Percent */
            co2_percent: number;
            /** He Percent */
            he_percent: number;
            /** Suppressant */
            suppressant: string;
            /** Droplet Diameter Mm */
            droplet_diameter_mm: number | null;
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "Extinction" | "Completion" | "Disruption";
            /** Sustained */
            sustained: boolean;
            /** Burn Time S */
            burn_time_s: number | null;
            /** Qc Flags */
            qc_flags: string[];
            /** In Model Scope */
            in_model_scope: boolean;
            prediction: components["schemas"]["OutOfFoldPrediction"] | null;
            /** Source Id */
            source_id: string;
            /** Extinction Diameter Mm */
            extinction_diameter_mm: number | null;
            /** Burning Rate Mm2 S */
            burning_rate_mm2_s: number | null;
            source: components["schemas"]["SourceRef"];
            /** Notes */
            notes: string[];
        };
        /** ExperimentList */
        ExperimentList: {
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Items */
            items: components["schemas"]["ExperimentSummary"][];
        };
        /** ExperimentSummary */
        ExperimentSummary: {
            /** @default observed */
            provenance: components["schemas"]["Provenance"];
            /** Test Id */
            test_id: number;
            /** Flex Identifier */
            flex_identifier: string;
            /** Datetime Gmt */
            datetime_gmt: string;
            fuel: components["schemas"]["Fuel"];
            /** Pressure Atm */
            pressure_atm: number | null;
            /** Pressure Level */
            pressure_level: string;
            /** Oxygen Percent */
            oxygen_percent: number;
            /** Nitrogen Percent */
            nitrogen_percent: number;
            /** Co2 Percent */
            co2_percent: number;
            /** He Percent */
            he_percent: number;
            /** Suppressant */
            suppressant: string;
            /** Droplet Diameter Mm */
            droplet_diameter_mm: number | null;
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "Extinction" | "Completion" | "Disruption";
            /** Sustained */
            sustained: boolean;
            /** Burn Time S */
            burn_time_s: number | null;
            /** Qc Flags */
            qc_flags: string[];
            /** In Model Scope */
            in_model_scope: boolean;
            prediction: components["schemas"]["OutOfFoldPrediction"] | null;
            /** Source Id */
            source_id: string;
        };
        /** Explanation */
        Explanation: {
            /** @default explanation */
            provenance: components["schemas"]["Provenance"];
            /** Method */
            method: string;
            /**
             * Base Value
             * @description Average Fire Risk over the training tests
             */
            base_value: number;
            /** Contributions */
            contributions: components["schemas"]["Contribution"][];
            /** Note */
            note: string;
        };
        /**
         * Fuel
         * @enum {string}
         */
        Fuel: "Methanol" | "Heptane";
        /** FuelDomain */
        FuelDomain: {
            /** Oxygen Percent */
            oxygen_percent: [
                number,
                number
            ];
            /** Co2 Percent */
            co2_percent: [
                number,
                number
            ];
            /** He Percent */
            he_percent: [
                number,
                number
            ];
            /** Droplet Diameter Mm */
            droplet_diameter_mm: [
                number,
                number
            ];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Api Version */
            api_version: string;
            /** Model */
            model: string;
            /** Training Tests */
            training_tests: number;
            /** Data Sha256 */
            data_sha256: string;
        };
        /** ImportanceRow */
        ImportanceRow: {
            /** Player */
            player: string;
            /** Mean Abs Points */
            mean_abs_points: number;
            /** Share */
            share: number;
        };
        /** Interpretation */
        Interpretation: {
            /** @default interpretation */
            provenance: components["schemas"]["Provenance"];
            /**
             * Method
             * @default Fixed template filled from the model outputs (no language model)
             */
            method: string;
            /** Text */
            text: string;
        };
        /** MetricWithInterval */
        MetricWithInterval: {
            /** Name */
            name: string;
            /** Nested Mean */
            nested_mean: number;
            /** Nested Sd */
            nested_sd: number;
            /** Pooled Estimate */
            pooled_estimate: number | null;
            /** Pooled Ci Low */
            pooled_ci_low: number | null;
            /** Pooled Ci High */
            pooled_ci_high: number | null;
        };
        /** ModelInfoResponse */
        ModelInfoResponse: {
            /** @default evaluation */
            provenance: components["schemas"]["Provenance"];
            /** Name */
            name: string;
            /** Features */
            features: string[];
            /** Standardised Coefficients */
            standardised_coefficients: {
                [key: string]: number;
            };
            /** Training Tests */
            training_tests: number;
            /** Training Sustained */
            training_sustained: number;
            /** Validation */
            validation: string;
            /** Metrics */
            metrics: components["schemas"]["MetricWithInterval"][];
            /** Calibration */
            calibration: components["schemas"]["CalibrationBin"][];
            /** Bands */
            bands: components["schemas"]["BandRow"][];
            /** Subgroups */
            subgroups: components["schemas"]["SubgroupRow"][];
            /** Global Importance */
            global_importance: components["schemas"]["ImportanceRow"][];
            /** Consistently Missed Test Ids */
            consistently_missed_test_ids: number[];
            /** Limitations */
            limitations: string[];
        };
        /** ModelSummary */
        ModelSummary: {
            /** @default evaluation */
            provenance: components["schemas"]["Provenance"];
            /** Name */
            name: string;
            /** Validation */
            validation: string;
            /** Roc Auc */
            roc_auc: number;
            /** Roc Auc Sd */
            roc_auc_sd: number;
            /** Pr Auc */
            pr_auc: number;
            /** Brier */
            brier: number;
            /** Recall At Alert */
            recall_at_alert: number;
            /** Precision At Alert */
            precision_at_alert: number;
            /** Calibration Slope Min */
            calibration_slope_min: number;
            /** Calibration Slope Max */
            calibration_slope_max: number;
            /** Alert Threshold Score */
            alert_threshold_score: number;
        };
        /** ObservedPoint */
        ObservedPoint: {
            /** Test Id */
            test_id: number;
            fuel: components["schemas"]["Fuel"];
            /** Pressure Level */
            pressure_level: string;
            /** Suppressant */
            suppressant: string;
            /** Oxygen Percent */
            oxygen_percent: number;
            /** Co2 Percent */
            co2_percent: number;
            /** He Percent */
            he_percent: number;
            /** Droplet Diameter Mm */
            droplet_diameter_mm: number | null;
            /** Outcome */
            outcome: string;
            /** Sustained */
            sustained: boolean;
        };
        /** OutOfFoldPrediction */
        OutOfFoldPrediction: {
            /** @default prediction */
            provenance: components["schemas"]["Provenance"];
            /**
             * Method
             * @default Out-of-fold: predicted by models that never saw this test (mean of 5 CV repeats)
             */
            method: string;
            /** Fire Risk */
            fire_risk: number;
            risk_level: components["schemas"]["RiskLevel"];
            /** Sustained Probability */
            sustained_probability: number;
        };
        /** PathStep */
        PathStep: {
            /** Step */
            step: string;
            /** Change */
            change: string;
            /** Fire Risk */
            fire_risk: number;
            /** Delta */
            delta: number;
            risk_level: components["schemas"]["RiskLevel"];
            /** Supported */
            supported: boolean;
        };
        /** PredictResponse */
        PredictResponse: {
            /** @default prediction */
            provenance: components["schemas"]["Provenance"];
            conditions: components["schemas"]["Conditions"];
            /** Fire Risk */
            fire_risk: number;
            risk_level: components["schemas"]["RiskLevel"];
            /** Sustained Probability */
            sustained_probability: number;
            /** Extinction Probability */
            extinction_probability: number;
            evidence: components["schemas"]["Evidence"];
            explanation: components["schemas"]["Explanation"];
            interpretation: components["schemas"]["Interpretation"];
            /** Model */
            model: string;
            /** Scope */
            scope: string;
        };
        /**
         * Provenance
         * @enum {string}
         */
        Provenance: "observed" | "prediction" | "estimate" | "explanation" | "interpretation" | "hypothetical" | "evaluation";
        /** RankingItem */
        RankingItem: {
            /** Rank */
            rank: number;
            /** Value */
            value: number;
            experiment: components["schemas"]["ExperimentSummary"];
        };
        /** RankingResponse */
        RankingResponse: {
            /** By */
            by: string;
            /** Metric Label */
            metric_label: string;
            provenance: components["schemas"]["Provenance"];
            /** Method */
            method: string;
            /** Items */
            items: components["schemas"]["RankingItem"][];
        };
        /**
         * RiskLevel
         * @enum {string}
         */
        RiskLevel: "LOW" | "ELEVATED" | "HIGH";
        /** ScenarioResult */
        ScenarioResult: {
            /** @default prediction */
            provenance: components["schemas"]["Provenance"];
            conditions: components["schemas"]["Conditions"];
            /** Fire Risk */
            fire_risk: number;
            risk_level: components["schemas"]["RiskLevel"];
            /** Sustained Probability */
            sustained_probability: number;
            /** Supported By Data */
            supported_by_data: boolean;
            /** In Tested Range */
            in_tested_range: boolean;
            /** Warnings */
            warnings: string[];
        };
        /** SeriesComparison */
        SeriesComparison: {
            fuel: components["schemas"]["Fuel"];
            /** Pressure Level */
            pressure_level: string;
            /** Suppressants */
            suppressants: string[];
            /** Intervals Overlap */
            intervals_overlap: boolean;
            /** Statement */
            statement: string;
        };
        /** SeriesEstimate */
        SeriesEstimate: {
            /** @default estimate */
            provenance: components["schemas"]["Provenance"];
            fuel: components["schemas"]["Fuel"];
            /** Pressure Level */
            pressure_level: string;
            /** Suppressant */
            suppressant: string;
            /** Tests */
            tests: number;
            /** Sustained */
            sustained: number;
            /** Extinguished */
            extinguished: number;
            /** Oxygen Tested Min */
            oxygen_tested_min: number;
            /** Oxygen Tested Max */
            oxygen_tested_max: number;
            /** Estimable */
            estimable: boolean;
            /** O2 50 Percent */
            o2_50_percent: number | null;
            /** Ci Low Percent */
            ci_low_percent: number | null;
            /** Ci High Percent */
            ci_high_percent: number | null;
            /** Ci Beyond Tested */
            ci_beyond_tested: boolean;
            /** Suppressant Percent At O2 50 */
            suppressant_percent_at_o2_50: number | null;
            /** Status */
            status: string;
        };
        /** SimilarItem */
        SimilarItem: {
            /**
             * Similarity
             * @description 0-100; 100 = identical tested condition
             */
            similarity: number;
            /** Distance */
            distance: number;
            experiment: components["schemas"]["ExperimentSummary"];
        };
        /**
         * SimilarRequest
         * @example {
         *       "droplet_diameter_mm": 3,
         *       "fuel": "Methanol",
         *       "oxygen_percent": 21,
         *       "suppressant": "CO2",
         *       "suppressant_percent": 10
         *     }
         */
        SimilarRequest: {
            fuel: components["schemas"]["Fuel"];
            /**
             * Oxygen Percent
             * @description O2 mole fraction in percent (air = 21).
             */
            oxygen_percent: number;
            /**
             * @description Added diluent gas; 'none' = O2/N2 only.
             * @default none
             */
            suppressant: components["schemas"]["Suppressant"];
            /**
             * Suppressant Percent
             * @description Suppressant mole fraction in percent.
             * @default 0
             */
            suppressant_percent: number;
            /**
             * Droplet Diameter Mm
             * @description Initial droplet diameter in mm.
             */
            droplet_diameter_mm: number;
            /**
             * K
             * @description Number of similar tests to return
             * @default 5
             */
            k: number;
        };
        /** SimilarResponse */
        SimilarResponse: {
            /** @default observed */
            provenance: components["schemas"]["Provenance"];
            /** Method */
            method: string;
            query: components["schemas"]["Conditions"];
            /** Support Radius */
            support_radius: number;
            /** Items */
            items: components["schemas"]["SimilarItem"][];
        };
        /** Source */
        Source: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "dataset" | "report";
            /** Publisher */
            publisher: string;
            /** Url */
            url: string;
            /** Doi */
            doi: string | null;
            /** License */
            license: string | null;
            /** Citation */
            citation: string;
            /** Used For */
            used_for: string;
        };
        /** SourceRef */
        SourceRef: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Url */
            url: string;
            /** Doi */
            doi?: string | null;
        };
        /** StatsResponse */
        StatsResponse: {
            /** @default observed */
            provenance: components["schemas"]["Provenance"];
            /** Program */
            program: string;
            /** Nasa Investigations */
            nasa_investigations: number;
            /** Nasa Sources */
            nasa_sources: number;
            experiments: components["schemas"]["ExperimentCounts"];
            /** Fuels */
            fuels: string[];
            /** Suppressants Tested */
            suppressants_tested: string[];
            /** Pressure Levels */
            pressure_levels: string[];
            /** Date Start */
            date_start: string;
            /** Date End */
            date_end: string;
            model: components["schemas"]["ModelSummary"];
        };
        /** SubgroupRow */
        SubgroupRow: {
            /** Subgroup */
            subgroup: string;
            /** Tests */
            tests: number;
            /** Sustained */
            sustained: number;
            /** Roc Auc */
            roc_auc: number | null;
            /** Recall */
            recall: number | null;
            /** Missed Fires */
            missed_fires: number;
            /** False Alarms */
            false_alarms: number;
        };
        /**
         * Suppressant
         * @enum {string}
         */
        Suppressant: "none" | "CO2" | "He";
        /** SuppressantsResponse */
        SuppressantsResponse: {
            /** @default observed */
            observed_provenance: components["schemas"]["Provenance"];
            /** @default estimate */
            estimate_provenance: components["schemas"]["Provenance"];
            /** Method */
            method: string;
            /** Observed */
            observed: components["schemas"]["ObservedPoint"][];
            /** Estimates */
            estimates: components["schemas"]["SeriesEstimate"][];
            /** Comparisons */
            comparisons: components["schemas"]["SeriesComparison"][];
            /** Conclusion */
            conclusion: string;
            /** Caveats */
            caveats: string[];
        };
        /** Sweep */
        Sweep: {
            /**
             * Feature
             * @enum {string}
             */
            feature: "oxygen" | "droplet";
            /** Label */
            label: string;
            /** Unit */
            unit: string;
            /** Points */
            points: components["schemas"]["SweepPoint"][];
        };
        /** SweepPoint */
        SweepPoint: {
            /** X */
            x: number;
            /** A */
            a: number | null;
            /** B */
            b: number | null;
            /** A Supported */
            a_supported: boolean;
            /** B Supported */
            b_supported: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WhatIfRequest */
        WhatIfRequest: {
            scenario_a: components["schemas"]["Conditions"];
            scenario_b: components["schemas"]["Conditions"];
            /**
             * Sweep
             * @default oxygen
             */
            sweep: ("oxygen" | "droplet") | null;
            /**
             * Sweep Points
             * @default 40
             */
            sweep_points: number;
        };
        /** WhatIfResponse */
        WhatIfResponse: {
            /** @default hypothetical */
            provenance: components["schemas"]["Provenance"];
            a: components["schemas"]["ScenarioResult"];
            b: components["schemas"]["ScenarioResult"];
            /** Delta */
            delta: number;
            /** Path */
            path: components["schemas"]["PathStep"][];
            sweep: components["schemas"]["Sweep"] | null;
            /** Notes */
            notes: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    stats_api_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsResponse"];
                };
            };
        };
    };
    sources_api_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Source"][];
                };
            };
        };
    };
    domain_api_domain_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainResponse"];
                };
            };
        };
    };
    model_api_model_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelInfoResponse"];
                };
            };
        };
    };
    list_experiments_api_experiments_get: {
        parameters: {
            query?: {
                fuel?: components["schemas"]["Fuel"] | null;
                suppressant?: components["schemas"]["Suppressant"] | null;
                pressure_level?: ("0.7atm" | "1atm" | "2-3atm") | null;
                outcome?: ("Extinction" | "Completion" | "Disruption") | null;
                in_model_scope?: boolean | null;
                oxygen_min?: number | null;
                oxygen_max?: number | null;
                /** @description FLEX identifier fragment or exact test number */
                search?: string | null;
                sort?: "test_id" | "-test_id" | "oxygen" | "-oxygen" | "risk" | "-risk" | "date" | "-date";
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_experiment_api_experiments__test_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                test_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    predict_api_predict_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Conditions"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    what_if_api_what_if_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WhatIfRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhatIfResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ranking_api_ranking_get: {
        parameters: {
            query?: {
                by?: "risk" | "lowest_risk" | "extinction" | "burn_time";
                fuel?: components["schemas"]["Fuel"] | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    condition_ranking_api_ranking_conditions_get: {
        parameters: {
            query?: {
                order?: "desc" | "asc";
                min_tests?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConditionRankingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    suppressants_api_suppressants_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuppressantsResponse"];
                };
            };
        };
    };
    similar_api_similar_experiments_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimilarRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimilarResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
